{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoring.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kaldrix.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kaldrix.annotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

{{- if .Values.monitoring.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.monitoring.serviceAccount.name }}
  labels:
    {{- include "kaldrix.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kaldrix.annotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- if .Values.monitoring.rbac.rules }}
  {{- toYaml .Values.monitoring.rbac.rules | nindent 2 }}
{{- else }}
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["get", "list", "watch"]
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.monitoring.serviceAccount.name }}
  labels:
    {{- include "kaldrix.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kaldrix.annotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.monitoring.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.monitoring.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
{{- end }}