{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kaldrix.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kaldrix.annotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
    - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
    
    - job_name: 'kubernetes-nodes'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
    
    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https
    
    - job_name: 'kaldrix-frontend'
      static_configs:
      - targets: ['frontend-service:3000']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'kaldrix-backend'
      static_configs:
      - targets: ['backend-service:3001']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'kaldrix-blockchain'
      static_configs:
      - targets: ['blockchain-service:8545']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'postgres'
      static_configs:
      - targets: ['postgres-service:5432']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    - job_name: 'redis'
      static_configs:
      - targets: ['redis-service:6379']
      metrics_path: '/metrics'
      scrape_interval: 30s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kaldrix.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kaldrix.annotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  alerts.yml: |
    groups:
    - name: kaldrix-alerts
      rules:
      {{- if .Values.monitoring.alerts.enabled }}
      {{- range .Values.monitoring.alerts.rules }}
      - alert: {{ .alert }}
        expr: {{ .expr }}
        for: {{ .for }}
        labels:
          {{- toYaml .labels | nindent 10 }}
        annotations:
          {{- toYaml .annotations | nindent 10 }}
      {{- end }}
      {{- end }}
{{- end }}